on:
  push:
     branches:
       - main
  schedule:
    - cron:  '0 3 * * *'

name: pycoins-render

jobs:
  bookdown:
    name: renderbook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Environment Variables
        run: echo APIKEY=${{ secrets.APIKEY }} >> .env
      - name: Render Book from Action
        uses: ckrusemd/jupyterbook-action@v0.17
        with:
          generatefile: generate_files.ipynb
      - uses: actions/upload-artifact@v1
        with:
          name: _build
          path: _build/

  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: _build # optional
        path: _build/ # optional
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      with:
        build_dir: _build/html/
        email: ${{ secrets.EMAIL }}  #optional
        jekyll: no                     # optional
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EMAIL: ${{ secrets.EMAIL }}
        BUILD_DIR: _build/
